name: Sanity

on:
  pull_request:

jobs:
  sanity:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Sanity Check Script
        run: " bash sanity.sh"
